---
# tasks file for nodejs_setup
# installing nodejs and npm in SUSE
- name: Installing nodejs and npm
  become: yes
  zypper: 
    name: ['{{ nodejs_version }}','npm']
    state: present
    update_cache: yes
